export const products = [
  {
    id: "1",
    name: "Lace Shirt Cut II",
    price: 14,
    currency: "$",
    image: "/images/product1.png",
    hoverImage: "/images/product1-hover.png",
    bestSeller: false,
    newReleased: true,
    sales: true,
  },
  {
    id: "2",
    name: "Lace Shirt Cut II",
    price: 24,
    currency: "$",
    image: "/images/product2.png",
    hoverImage: "/images/product2-hover.png",
    bestSeller: true,
    newReleased: false,
    sales: false,
  },
  {
    id: "3",
    name: "Lace Shirt Cut II",
    price: 40,
    currency: "$",
    image: "/images/product3.png",
    hoverImage: "/images/product1-hover.png",
    bestSeller: false,
    newReleased: true,
    sales: true,
  },
  {
    id: "4",
    name: "Lace Shirt Cut II",
    price: 54,
    currency: "$",
    image: "/images/product4.png",
    hoverImage: "/images/product2-hover.png",
    bestSeller: true,
    newReleased: false,
    sales: true,
  },
];
